### PR TITLE
Migrate `amfora` to Homebrew core tap

### PR DESCRIPTION
**Pull request by vladimyr**
Formula for `amfora` got accepted to Homebrew core tap. 
 
 Related: https://github.com/makeworld-the-better-one/amfora/pull/247

### CODE REVIEW

**Comment by makew0rld** [comment]
What about people who want to install Amfora from HEAD? Can that stay, but non-HEAD installs be redirected?

Thank you for setting this up.

**Comment by vladimyr** [comment]
> What about people who want to install Amfora from HEAD?

They can use simply use: `brew install --head amfora`

image

> Can that stay, but non-HEAD installs be redirected?

AFAIK there is no way to _partially migrate_ because there is no need to 🤷  With that being said you could keep the formula around but `tap-migrations.json` will redirect users to core tap. 

> Thank you for setting this up.

Thank you for building amfora!

**Comment by makew0rld** [comment]
What I'm asking is if people who installed Amfora from HEAD using this repo will still be able to receive HEAD updates. Do you know about that? Sorry if I'm misunderstanding.

**Comment by vladimyr** [comment]
Hmm, that's an interesting question. TBH I don't know the answer but I'll try to check it out.

**Comment by makew0rld** [comment]
Thanks. Let me know here if you find the answer.

**Pull request merged**
